version: '3'
services:
  t3docmake:
    platform: linux/amd64
    image: ghcr.io/t3docs/render-documentation:latest
    command: makehtml
    volumes:
      - ./:/PROJECT:ro
      - ./Documentation-GENERATED-temp:/RESULT
