services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebVision\WvDeepltranslate\:
    resource: '../Classes/*'
    exclude: '../Classes/{Domain/Model,Override/DatabaseRecordList.php,Override/v10/DatabaseRecordList.php}'
