services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebVision\WvDeepltranslate\:
    resource: '../Classes/*'
    exclude: '../Classes/{Domain/Model,Override/DatabaseRecordList.php,Override/v10/DatabaseRecordList.php}'

  WebVision\WvDeepltranslate\Command\GlossariesEntriesCleanupCommand:
    tags:
      - name: 'console.command'
        command: 'wv_deepltranslate:glossary_cleanup'

  WebVision\WvDeepltranslate\Command\GlossariesEntriesListCommand:
    tags:
      - name: 'console.command'
        command: 'wv_deepltranslate:glossary_list'

  WebVision\WvDeepltranslate\Hooks\DataHandlerHook:
    public: true

  WebVision\WvDeepltranslate\Service\DeeplService:
    arguments:
      $cache: '@cache.wvdeepltranslate'

  cache.wvdeepltranslate:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'wvdeepltranslate' ]
