name: tests core 9

# @todo v9 disabled, due multiple out-of-sync dependencies (news to high for core v9) and other issues
on:
  push:
  pull_request:
  schedule:
    - cron: '56 4 * * *'

jobs:
  testsuite:
    name: all tests with core v9
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '7.4']
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2.2

      - name: "Prepare composer dependencies"
        run: "Build/Scripts/composer-for-core-version.sh 9"

      - name: "Run TypoScript lint"
        run: "composer lint:typoscript"

      - name: "Run PHP lint"
        run: "composer lint:php"

      - name: "Verify code cgl"
        run: "composer cs:check"

      # @todo Disabled because of PHPStan errors - tricky to handle properly agaist wide range of core versions. Tackle
      #       after branching and minimizing version range.
      #      - name: "Run PHPStan"
      #        run: "composer analyze:php"

      - name: "Unit tests"
        run: "composer test:php:unit"

# @todo Functional tests disabled for now - testing against real DeepL API needs an API key. Testing against live API
#       should be rethinked and tackled otherwise, e.g. using https://github.com/DeepLcom/deepl-mock. The DeepL php
#       API client also uses this mockserver for testing - maybe it is usable.
#
#      - name: "Start MySQL"
#        run: "sudo /etc/init.d/mysql start"
#
#      - name: "Functional tests"
#        run: |
#          export typo3DatabaseName="$DB_DATABASE";
#          export typo3DatabaseHost="$DB_HOST";
#          export typo3DatabaseUsername="$DB_USER";
#          export typo3DatabasePassword="$DB_PASSWORD";
#          composer test:php:functional
